language: csharp
mono: none
dotnet: 3.1.202
sudo: required

before_script:
- choco install mssqlserver2014-sqllocaldb
- powershell -Command "Set-ExecutionPolicy Bypass"

script:
  - dotnet restore
  - dotnet build
  - dotnet test
